version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"

  beat_beat:
    build:
      context: .
      dockerfile: ./celery_beat/Dockerfile

  beat_worker:
    build:
      context: .
      dockerfile: ./celery_worker/Dockerfile
