"""Initial migration

Revision ID: 7e7fdd2796ac
Revises: 
Create Date: 2022-08-25 14:22:14.339560+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from src.migrations.seed import seed_initial_migration

revision = '7e7fdd2796ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_alerts',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('is_limit_set', sa.Boolean(), nullable=False),
                    sa.Column('limit', sa.Integer(), nullable=False),
                    sa.Column('threshold', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_bill_alerts_company_id'), 'bill_alerts', ['company_id'], unique=True)
    op.create_table('card_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coupon_discount_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coupon_recurrency_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coupon_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('default_plans',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('free_requests', sa.Integer(), nullable=False),
                    sa.Column('cost_per_thousand_requests', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('invoice_item_types',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('invoice_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payment_attempt_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payment_methods',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('method', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('stripe_customers',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('stripe_customer_id', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company_id')
                    )
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'],
                    unique=False)
    op.create_table('subscription_coupon_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscription_statuses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cards',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('stripe_payment_method_id', sa.String(length=50), nullable=False),
                    sa.Column('brand', sa.String(length=50), nullable=True),
                    sa.Column('last_four', sa.String(length=4), nullable=False),
                    sa.Column('exp_month', sa.Integer(), nullable=False),
                    sa.Column('exp_year', sa.Integer(), nullable=False),
                    sa.Column('fingerprint', sa.String(length=50), nullable=False),
                    sa.Column('funding', sa.String(length=50), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['card_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cards_company_id'), 'cards', ['company_id'], unique=False)
    op.create_table('coupons',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('code', sa.String(length=30), nullable=False),
                    sa.Column('valid_from', sa.Date(), nullable=False),
                    sa.Column('valid_until', sa.Date(), nullable=False),
                    sa.Column('discount_type_id', sa.Integer(), nullable=False),
                    sa.Column('discount_amount', sa.Integer(), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('usage_count', sa.Integer(), nullable=False),
                    sa.Column('max_usage_count', sa.Integer(), nullable=True),
                    sa.Column('recurrency_type_id', sa.Integer(), nullable=False),
                    sa.Column('company_id', sa.String(length=36), nullable=True),
                    sa.ForeignKeyConstraint(['discount_type_id'], ['coupon_discount_types.id'], ),
                    sa.ForeignKeyConstraint(['recurrency_type_id'], ['coupon_recurrency_types.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['coupon_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_name'), 'coupons', ['name'], unique=False)
    op.create_table('subscriptions',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('is_current', sa.Boolean(), nullable=False),
                    sa.Column('is_free_requests_used', sa.Boolean(), nullable=False),
                    sa.Column('is_stop_generation', sa.Boolean(), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.Column('free_requests', sa.Integer(), nullable=False),
                    sa.Column('cost_per_thousand_requests', sa.Integer(), nullable=False),
                    sa.Column('is_enterprise', sa.Boolean(), nullable=False),
                    sa.Column('payment_method_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['subscription_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subscriptions_company_id'), 'subscriptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_end_date'), 'subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_current'), 'subscriptions', ['is_current'], unique=False)
    op.create_index(op.f('ix_subscriptions_start_date'), 'subscriptions', ['start_date'], unique=False)
    op.create_table('invoices',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('subscription_id', sa.String(length=36), nullable=False),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('total_requests', sa.Integer(), nullable=False),
                    sa.Column('invoice_url', sa.String(length=255), nullable=True),
                    sa.Column('receipt_url', sa.String(length=255), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['status_id'], ['invoice_statuses.id'], ),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_table('subscription_coupons',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('subscription_id', sa.String(length=36), nullable=False),
                    sa.Column('coupon_id', sa.String(length=36), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['subscription_coupon_statuses.id'], ),
                    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_subscription_coupons_coupon_id'), 'subscription_coupons', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_subscription_coupons_subscription_id'), 'subscription_coupons', ['subscription_id'],
                    unique=False)
    op.create_table('invoice_items',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('invoice_id', sa.String(length=36), nullable=False),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('unit_amount', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('stripe_invoice_item_id', sa.String(length=50), nullable=True),
                    sa.Column('type_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='cascade'),
                    sa.ForeignKeyConstraint(['type_id'], ['invoice_item_types.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payment_attempts',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('modified_date', sa.DateTime(), nullable=True),
                    sa.Column('company_id', sa.String(length=36), nullable=False),
                    sa.Column('invoice_id', sa.String(length=36), nullable=False),
                    sa.Column('card_id', sa.String(length=36), nullable=True),
                    sa.Column('stripe_payment_method_id', sa.String(length=50), nullable=True),
                    sa.Column('stripe_invoice_id', sa.String(length=50), nullable=True),
                    sa.Column('stripe_payment_intent_id', sa.String(length=50), nullable=True),
                    sa.Column('stripe_charge_id', sa.String(length=50), nullable=True),
                    sa.Column('payment_method_id', sa.Integer(), nullable=False),
                    sa.Column('status_id', sa.Integer(), nullable=False),
                    sa.Column('hash_code', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
                    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='cascade'),
                    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
                    sa.ForeignKeyConstraint(['status_id'], ['payment_attempt_statuses.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('hash_code')
                    )
    op.create_index(op.f('ix_payment_attempts_company_id'), 'payment_attempts', ['company_id'], unique=False)
    # ### end Alembic commands ###

    # ### Manual seed ###
    seed_initial_migration()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_company_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_subscription_coupons_subscription_id'), table_name='subscription_coupons')
    op.drop_index(op.f('ix_subscription_coupons_coupon_id'), table_name='subscription_coupons')
    op.drop_table('subscription_coupons')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_start_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_current'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_end_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_company_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_coupons_name'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_cards_company_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('subscription_statuses')
    op.drop_table('subscription_coupon_statuses')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_table('stripe_customers')
    op.drop_table('payment_methods')
    op.drop_table('payment_attempt_statuses')
    op.drop_table('invoice_statuses')
    op.drop_table('invoice_item_types')
    op.drop_table('default_plans')
    op.drop_table('coupon_statuses')
    op.drop_table('coupon_recurrency_types')
    op.drop_table('coupon_discount_types')
    op.drop_table('card_statuses')
    op.drop_index(op.f('ix_bill_alerts_company_id'), table_name='bill_alerts')
    op.drop_table('bill_alerts')
    # ### end Alembic commands ###
